
####################################################################################
# Generated by PlanAhead 14.2 built on 'Fri Jul 20 18:52:11 MDT 2012' by 'xbuild'
####################################################################################


####################################################################################
# Constraints from file : 'icon.xncf'
####################################################################################





#// Timing Constraints
#// Timing Constraints

# All timing constraint translations are rough conversions, intended to act as a template for further manual refinement. The translations should not be expected to produce semantically identical results to the original ucf. Each xdc timing constraint must be manually inspected and verified to ensure it captures the desired intent

# In xdc, all clocks are related by default. This differs from ucf, where clocks are unrelated unless specified otherwise. As a result, you may now see cross-clock paths that were previously unconstrained in ucf. Commented out xdc false path constraints have been generated and can be uncommented, should you wish to remove these new paths. These commands are located after the last clock definition

# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/ise_mcb_phase_test_ise12migration/.Xil/PlanAhead-3664-XSHCHUNXIA30/ngc2edif/icon.xncf:6
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name DRCK_LOCAL_O -period 30.000 [get_pins gen_dbg_enable.my_icon_c3/U0/U_ICON/I_YES_BSCAN.U_BS/I_USE_SOFTBSCAN_EQ0.I_USE_XST_TCK_WORKAROUND_EQ1.U_ICON_BSCAN_BUFG/U_BUFG/O]


#// Timing Constraints
#// Timing Constraints

# The following constraint had some error while parsing ucf input. It will not be converted. Please fix the error and then try again.
#
#TIMESPEC TS_U_TO_J = FROM "U_CLK" TO "J_CLK" 15000.000000000 pS ;
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/ise_mcb_phase_test_ise12migration/.Xil/PlanAhead-3664-XSHCHUNXIA30/ngc2edif/icon.xncf:9
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [get_clocks DRCK_LOCAL_O]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [get_clocks DRCK_LOCAL_O]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [get_clocks DRCK_LOCAL_O]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [get_clocks DRCK_LOCAL_O]

# The following constraint had some error while parsing ucf input. It will not be converted. Please fix the error and then try again.
#
#TIMESPEC TS_U_TO_U = FROM "U_CLK" TO "U_CLK" 15000.000000000 pS ;
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/ise_mcb_phase_test_ise12migration/.Xil/PlanAhead-3664-XSHCHUNXIA30/ngc2edif/icon.xncf:10
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]]
set_max_delay 15.000 -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_icon_c3/U0/iUPDATE_OUT]]

# The following constraint had some error while parsing ucf input. It will not be converted. Please fix the error and then try again.
#
#TIMESPEC TS_J_TO_D = FROM "J_CLK" TO "D_CLK" TIG ;
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/ise_mcb_phase_test_ise12migration/.Xil/PlanAhead-3664-XSHCHUNXIA30/ngc2edif/icon.xncf:11
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]]
set_false_path -from [get_clocks DRCK_LOCAL_O] -to [all_fanout -endpoints_only -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]]

# The following constraint had some error while parsing ucf input. It will not be converted. Please fix the error and then try again.
#
#TIMESPEC TS_D_TO_J = FROM "D_CLK" TO "J_CLK" TIG ;
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/ise_mcb_phase_test_ise12migration/.Xil/PlanAhead-3664-XSHCHUNXIA30/ngc2edif/icon.xncf:12
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets {gen_dbg_enable.my_vio_c3/ASYNC_OUT[0]}]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]] -to [get_clocks DRCK_LOCAL_O]
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets gen_dbg_enable.my_ila_c3/CLK]] -to [get_clocks DRCK_LOCAL_O]



####################################################################################
# Constraints from file : 'ila.xncf'
####################################################################################




####################################################################################
# Constraints from file : 'vio.xncf'
####################################################################################




####################################################################################
# Constraints from file : 'example_top.ucf'
####################################################################################

############################################################################
## 
##  Xilinx, Inc. 2006            www.xilinx.com 
##  Tue Jun 21 08:54:31 2011
##  Generated by MIG Version 3.8
##  
############################################################################
##  File name :       example_top.ucf
## 
##  Details :     Constraints file
##                    FPGA family:       spartan6
##                    FPGA:              xc6slx16-csg324
##                    Speedgrade:        -2
##                    Design Entry:      VERILOG
##                    Design:            with Test bench
##                    DCM Used:          Enable
##                    No.Of Memory Controllers: 1
##
############################################################################ 
## Target SP601 board 
## Updates to UCF file for SP601 board:
##   1. LOC 200MHz differential "sys_clk" inputs to K15(P) and K16(N)
##   2. LOC "sys_rst_n" input to SP601 CPU_RESET switch = N4 (LVCMOS18)
##   3. Add four GPIO_LED signals (2.5V bank voltage)
##   4. Change sys_clk_ibufg period constraint from 3.33ns to 5ns
##   5. Comment out "SP601 NET "c?_pll_lock" TIG;" parameter. 
############################################################################
# VCC AUX VOLTAGE 
############################################################################
set_property VCCAUX 2.5 [current_design]
# Valid values are 2.5 and 3.3

############################################################################
# DDR2 requires the MCB to operate in Extended performance mode with higher Vccint
# specification to achieve maximum frequency. Therefore, the following CONFIG constraint
# follows the corresponding GUI option setting. However, DDR3 can operate at higher 
# frequencies with any Vcciint value by operating MCB in extended mode. Please do not
# remove/edit the below constraint to avoid false errors.
############################################################################
set_property MCB_PERFORMANCE STANDARD [current_design]


##################################################################################
# Timing Ignore constraints for paths crossing the clock domain 
##################################################################################
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:45
set_false_path -through [get_nets memc?_wrapper_inst/mcb_ui_top_inst/mcb_raw_wrapper_inst/selfrefresh_mcb_mode]
## SP601 NET "c?_pll_lock" TIG;
#FIXME,Chandler, no error before, no related modification, comment first anyway, INST "memc?_wrapper_inst/mcb_ui_top_inst/mcb_raw_wrapper_inst/gen_term_calib.mcb_soft_calibration_top_inst/mcb_soft_calibration_inst/DONE_SOFTANDHARD_CAL*" TIG;

#Please uncomment the below TIG if used in a design which enables self-refresh mode
#NET "memc?_wrapper_inst/mcb_ui_top_inst/mcb_raw_wrapper_inst/gen_term_calib.mcb_soft_calibration_top_inst/mcb_soft_calibration_inst/SELFREFRESH_MCB_REQ" TIG;
     
##This path exists for DDR2 only
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:52
set_false_path -through [get_nets memc?_wrapper_inst/mcb_ui_top_inst/mcb_raw_wrapper_inst/gen_term_calib.mcb_soft_calibration_top_inst/mcb_soft_calibration_inst/CKE_Train]


# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:58
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets drp_clk]] -to [all_fanout -endpoints_only -flat -from [get_nets c3_clk0]]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:59
set_false_path -from [all_fanout -endpoints_only -only_cells -flat -from [get_nets c3_mcb_drp_clk]] -to [all_fanout -endpoints_only -flat -from [get_nets c3_clk0]]
############################################################################
## Memory Controller 3                               
## Memory Device: DDR2_SDRAM->EDE1116ACBG-8E 
## Frequency: 312.5 MHz
## Time Period: 3200 ps
## Supported Part Numbers: EDE1116ACBG-8E
############################################################################

############################################################################
## Clock constraints                                                        
############################################################################
#// SP601
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:72
# A PERIOD placed on an internal net will result in a clock defined with an internal source. Any upstream source clock latency will not be analyzed
create_clock -name memc3_infrastructure_inst/sys_clk_ibufg -period 5.000 [get_pins memc3_infrastructure_inst/diff_input_clk.u_ibufg_sys_clk/O]

# The following cross clock domain false path constraints can be uncommented in order to mimic ucf constraints behavior (see message at the beginning of this file)
# set_false_path -from [get_clocks DRCK_LOCAL_O] -to [get_clocks memc3_infrastructure_inst/sys_clk_ibufg]
# set_false_path -from [get_clocks memc3_infrastructure_inst/sys_clk_ibufg] -to [get_clocks DRCK_LOCAL_O]

############################################################################

############################################################################
## I/O TERMINATION                                                          
############################################################################
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[0]' has been applied to the port object 'mcb3_dram_dq[0]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[0]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[10]' has been applied to the port object 'mcb3_dram_dq[10]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[10]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[11]' has been applied to the port object 'mcb3_dram_dq[11]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[11]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[12]' has been applied to the port object 'mcb3_dram_dq[12]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[12]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[13]' has been applied to the port object 'mcb3_dram_dq[13]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[13]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[14]' has been applied to the port object 'mcb3_dram_dq[14]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[14]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[15]' has been applied to the port object 'mcb3_dram_dq[15]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[15]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[1]' has been applied to the port object 'mcb3_dram_dq[1]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[1]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[2]' has been applied to the port object 'mcb3_dram_dq[2]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[2]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[3]' has been applied to the port object 'mcb3_dram_dq[3]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[3]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[4]' has been applied to the port object 'mcb3_dram_dq[4]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[4]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[5]' has been applied to the port object 'mcb3_dram_dq[5]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[5]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[6]' has been applied to the port object 'mcb3_dram_dq[6]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[6]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[7]' has been applied to the port object 'mcb3_dram_dq[7]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[7]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[8]' has been applied to the port object 'mcb3_dram_dq[8]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[8]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:78
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dq[9]' has been applied to the port object 'mcb3_dram_dq[9]'.
#set_property IN_TERM NONE [get_ports {mcb3_dram_dq[9]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:79
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dqs' has been applied to the port object 'mcb3_dram_dqs'.
#set_property IN_TERM NONE [get_ports mcb3_dram_dqs]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:80
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_dqs_n' has been applied to the port object 'mcb3_dram_dqs_n'.
#set_property IN_TERM NONE [get_ports mcb3_dram_dqs_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:81
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_udqs' has been applied to the port object 'mcb3_dram_udqs'.
#set_property IN_TERM NONE [get_ports mcb3_dram_udqs]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:82
# The conversion of 'IN_TERM' constraint on 'net' object 'mcb3_dram_udqs_n' has been applied to the port object 'mcb3_dram_udqs_n'.
#set_property IN_TERM NONE [get_ports mcb3_dram_udqs_n]

############################################################################
# Status Signals : Update to LVCMOS IOSTANDARD for SP601
############################################################################

# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:88
# The conversion of 'IOSTANDARD' constraint on 'net' object 'error' has been applied to the port object 'error'.
#set_property IOSTANDARD LVCMOS25 [get_ports error]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:89
# The conversion of 'IOSTANDARD' constraint on 'net' object 'calib_done' has been applied to the port object 'calib_done'.
#set_property IOSTANDARD LVCMOS25 [get_ports calib_done]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:90
# The conversion of 'IOSTANDARD' constraint on 'net' object 'pll_locked' has been applied to the port object 'pll_locked'.
#set_property IOSTANDARD LVCMOS25 [get_ports pll_locked]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:91
# The conversion of 'IOSTANDARD' constraint on 'net' object 'heartbeat' has been applied to the port object 'heartbeat'.
#set_property IOSTANDARD LVCMOS25 [get_ports heartbeat]

# SP601 GPIO_LED0 DS11
#set_property PACKAGE_PIN E13 [get_ports heartbeat]
# SP601 GPIO_LED1 DS12
#set_property PACKAGE_PIN C14 [get_ports error]
# SP601 GPIO_LED2 DS13
#set_property PACKAGE_PIN C4 [get_ports calib_done]
# SP601 GPIO_LED3 DS14
#set_property PACKAGE_PIN A4 [get_ports pll_locked]
############################################################################
# I/O STANDARDS 
############################################################################

# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[0]' has been applied to the port object 'mcb3_dram_dq[0]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[0]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[10]' has been applied to the port object 'mcb3_dram_dq[10]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[10]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[11]' has been applied to the port object 'mcb3_dram_dq[11]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[11]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[12]' has been applied to the port object 'mcb3_dram_dq[12]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[12]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[13]' has been applied to the port object 'mcb3_dram_dq[13]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[13]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[14]' has been applied to the port object 'mcb3_dram_dq[14]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[14]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[15]' has been applied to the port object 'mcb3_dram_dq[15]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[15]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[1]' has been applied to the port object 'mcb3_dram_dq[1]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[1]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[2]' has been applied to the port object 'mcb3_dram_dq[2]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[2]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[3]' has been applied to the port object 'mcb3_dram_dq[3]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[3]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[4]' has been applied to the port object 'mcb3_dram_dq[4]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[4]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[5]' has been applied to the port object 'mcb3_dram_dq[5]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[5]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[6]' has been applied to the port object 'mcb3_dram_dq[6]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[6]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[7]' has been applied to the port object 'mcb3_dram_dq[7]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[7]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[8]' has been applied to the port object 'mcb3_dram_dq[8]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[8]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:101
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dq[9]' has been applied to the port object 'mcb3_dram_dq[9]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_dq[9]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[0]' has been applied to the port object 'mcb3_dram_a[0]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[0]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[10]' has been applied to the port object 'mcb3_dram_a[10]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[10]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[11]' has been applied to the port object 'mcb3_dram_a[11]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[11]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[12]' has been applied to the port object 'mcb3_dram_a[12]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[12]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[1]' has been applied to the port object 'mcb3_dram_a[1]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[1]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[2]' has been applied to the port object 'mcb3_dram_a[2]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[2]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[3]' has been applied to the port object 'mcb3_dram_a[3]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[3]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[4]' has been applied to the port object 'mcb3_dram_a[4]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[4]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[5]' has been applied to the port object 'mcb3_dram_a[5]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[5]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[6]' has been applied to the port object 'mcb3_dram_a[6]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[6]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[7]' has been applied to the port object 'mcb3_dram_a[7]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[7]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[8]' has been applied to the port object 'mcb3_dram_a[8]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[8]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:102
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_a[9]' has been applied to the port object 'mcb3_dram_a[9]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_a[9]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ba[0]' has been applied to the port object 'mcb3_dram_ba[0]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_ba[0]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ba[1]' has been applied to the port object 'mcb3_dram_ba[1]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_ba[1]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:103
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ba[2]' has been applied to the port object 'mcb3_dram_ba[2]'.
#set_property IOSTANDARD SSTL18_II [get_ports {mcb3_dram_ba[2]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:104
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dqs' has been applied to the port object 'mcb3_dram_dqs'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_dqs]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:105
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_udqs' has been applied to the port object 'mcb3_dram_udqs'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_udqs]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:106
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dqs_n' has been applied to the port object 'mcb3_dram_dqs_n'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_dqs_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:107
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_udqs_n' has been applied to the port object 'mcb3_dram_udqs_n'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_udqs_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:108
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ck' has been applied to the port object 'mcb3_dram_ck'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_ck]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:109
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ck_n' has been applied to the port object 'mcb3_dram_ck_n'.
#set_property IOSTANDARD DIFF_SSTL18_II [get_ports mcb3_dram_ck_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:110
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_cke' has been applied to the port object 'mcb3_dram_cke'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_cke]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:111
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_ras_n' has been applied to the port object 'mcb3_dram_ras_n'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_ras_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:112
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_cas_n' has been applied to the port object 'mcb3_dram_cas_n'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_cas_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:113
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_we_n' has been applied to the port object 'mcb3_dram_we_n'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_we_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:114
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_odt' has been applied to the port object 'mcb3_dram_odt'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_odt]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:115
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_dm' has been applied to the port object 'mcb3_dram_dm'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_dm]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:116
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_dram_udm' has been applied to the port object 'mcb3_dram_udm'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_dram_udm]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:117
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_rzq' has been applied to the port object 'mcb3_rzq'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_rzq]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:118
# The conversion of 'IOSTANDARD' constraint on 'net' object 'mcb3_zio' has been applied to the port object 'mcb3_zio'.
#set_property IOSTANDARD SSTL18_II [get_ports mcb3_zio]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:119
# The conversion of 'IOSTANDARD' constraint on 'net' object 'c3_sys_clk_p' has been applied to the port object 'c3_sys_clk_p'.
#set_property IOSTANDARD LVDS_25 [get_ports c3_sys_clk_p]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:119
# The conversion of 'DIFF_TERM' constraint on 'net' object 'c3_sys_clk_p' has been applied to the port object 'c3_sys_clk_p'.
#set_property DIFF_TERM TRUE [get_ports c3_sys_clk_p]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:120
# The conversion of 'IOSTANDARD' constraint on 'net' object 'c3_sys_clk_n' has been applied to the port object 'c3_sys_clk_n'.
#set_property IOSTANDARD LVDS_25 [get_ports c3_sys_clk_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:120
# The conversion of 'DIFF_TERM' constraint on 'net' object 'c3_sys_clk_n' has been applied to the port object 'c3_sys_clk_n'.
#set_property DIFF_TERM TRUE [get_ports c3_sys_clk_n]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:121
# The conversion of 'IOSTANDARD' constraint on 'net' object 'c3_sys_rst_i' has been applied to the port object 'c3_sys_rst_i'.
#set_property IOSTANDARD LVCMOS18 [get_ports c3_sys_rst_i]
#set_property IOSTANDARD LVCMOS18 [get_ports RST_PLL]
##LVCMOS18;
#set_property IOSTANDARD LVCMOS25 [get_ports {STATE[0]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {STATE[1]}]
#set_property IOSTANDARD LVCMOS25 [get_ports {STATE[2]}]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:124
# The conversion of 'IOSTANDARD' constraint on 'net' object 'SSTEP' has been applied to the port object 'SSTEP'.
#set_property IOSTANDARD LVCMOS18 [get_ports SSTEP]
############################################################################
# MCB 3
# Pin Location Constraints for Clock, Masks, Address, and Controls
############################################################################

#set_property PACKAGE_PIN J7 [get_ports {mcb3_dram_a[0]}]
#set_property PACKAGE_PIN F4 [get_ports {mcb3_dram_a[10]}]
#set_property PACKAGE_PIN D3 [get_ports {mcb3_dram_a[11]}]
#set_property PACKAGE_PIN G6 [get_ports {mcb3_dram_a[12]}]
#set_property PACKAGE_PIN J6 [get_ports {mcb3_dram_a[1]}]
#set_property PACKAGE_PIN H5 [get_ports {mcb3_dram_a[2]}]
#set_property PACKAGE_PIN L7 [get_ports {mcb3_dram_a[3]}]
#set_property PACKAGE_PIN F3 [get_ports {mcb3_dram_a[4]}]
#set_property PACKAGE_PIN H4 [get_ports {mcb3_dram_a[5]}]
#set_property PACKAGE_PIN H3 [get_ports {mcb3_dram_a[6]}]
#set_property PACKAGE_PIN H6 [get_ports {mcb3_dram_a[7]}]
#set_property PACKAGE_PIN D2 [get_ports {mcb3_dram_a[8]}]
#set_property PACKAGE_PIN D1 [get_ports {mcb3_dram_a[9]}]
#set_property PACKAGE_PIN F2 [get_ports {mcb3_dram_ba[0]}]
#set_property PACKAGE_PIN F1 [get_ports {mcb3_dram_ba[1]}]
#set_property PACKAGE_PIN E1 [get_ports {mcb3_dram_ba[2]}]
#set_property PACKAGE_PIN K5 [get_ports mcb3_dram_cas_n]
#set_property PACKAGE_PIN G3 [get_ports mcb3_dram_ck]
#set_property PACKAGE_PIN G1 [get_ports mcb3_dram_ck_n]
#set_property PACKAGE_PIN H7 [get_ports mcb3_dram_cke]
#set_property PACKAGE_PIN K3 [get_ports mcb3_dram_dm]
#set_property PACKAGE_PIN L2 [get_ports {mcb3_dram_dq[0]}]
#set_property PACKAGE_PIN N2 [get_ports {mcb3_dram_dq[10]}]
#set_property PACKAGE_PIN N1 [get_ports {mcb3_dram_dq[11]}]
#set_property PACKAGE_PIN T2 [get_ports {mcb3_dram_dq[12]}]
#set_property PACKAGE_PIN T1 [get_ports {mcb3_dram_dq[13]}]
#set_property PACKAGE_PIN U2 [get_ports {mcb3_dram_dq[14]}]
#set_property PACKAGE_PIN U1 [get_ports {mcb3_dram_dq[15]}]
#set_property PACKAGE_PIN L1 [get_ports {mcb3_dram_dq[1]}]
#set_property PACKAGE_PIN K2 [get_ports {mcb3_dram_dq[2]}]
#set_property PACKAGE_PIN K1 [get_ports {mcb3_dram_dq[3]}]
#set_property PACKAGE_PIN H2 [get_ports {mcb3_dram_dq[4]}]
#set_property PACKAGE_PIN H1 [get_ports {mcb3_dram_dq[5]}]
#set_property PACKAGE_PIN J3 [get_ports {mcb3_dram_dq[6]}]
#set_property PACKAGE_PIN J1 [get_ports {mcb3_dram_dq[7]}]
#set_property PACKAGE_PIN M3 [get_ports {mcb3_dram_dq[8]}]
#set_property PACKAGE_PIN M1 [get_ports {mcb3_dram_dq[9]}]
#set_property PACKAGE_PIN L4 [get_ports mcb3_dram_dqs]
#set_property PACKAGE_PIN L3 [get_ports mcb3_dram_dqs_n]
#set_property PACKAGE_PIN K6 [get_ports mcb3_dram_odt]
#set_property PACKAGE_PIN L5 [get_ports mcb3_dram_ras_n]
# SP601 200MHz LVDS clock N
#set_property PACKAGE_PIN K16 [get_ports c3_sys_clk_n]
# SP601 200MHz LVDS clock P 
#set_property PACKAGE_PIN K15 [get_ports c3_sys_clk_p]
# SP601 CPU_RESET switch
#set_property PACKAGE_PIN N4 [get_ports c3_sys_rst_i]
#GPIO_BUTTON_0
#set_property PACKAGE_PIN P4 [get_ports RST_PLL]
#GPIO_BUTTON_1
#set_property PACKAGE_PIN F6 [get_ports SSTEP]
#GPIO_SWITCH_0
#set_property PACKAGE_PIN D14 [get_ports {STATE[0]}]
#GPIO_SWITCH_1
#set_property PACKAGE_PIN E12 [get_ports {STATE[1]}]
#GPIO_SWITCH_2
#set_property PACKAGE_PIN F12 [get_ports {STATE[2]}]
#NET  "rst_test"					LOC=A4;  # SP601 GPIO_LED3 DS14
#set_property PACKAGE_PIN K4 [get_ports mcb3_dram_udm]
#set_property PACKAGE_PIN P2 [get_ports mcb3_dram_udqs]
#set_property PACKAGE_PIN P1 [get_ports mcb3_dram_udqs_n]
#set_property PACKAGE_PIN E3 [get_ports mcb3_dram_we_n]

##################################################################################
#RZQ is required for all MCB designs.   Do not move the location #
#of this pin for ES devices.For production devices, RZQ can be moved to any #
#valid package pin within the MCB bank.For designs using Calibrated Input Termination, #
#a 2R resistor should be connected between RZQand ground, where R is the desired#
#input termination value.  Otherwise, RZQ should be left as a no-connect (NC) pin.#
##################################################################################
#set_property PACKAGE_PIN C2 [get_ports mcb3_rzq]
##################################################################################
#ZIO is only required for MCB designs using Calibrated Input Termination.#
#ZIO can be moved to any valid package pin (i.e. bonded IO) within the#
#MCB bank but must be left as a no-connect (NC) pin.#
##################################################################################
#set_property PACKAGE_PIN L6 [get_ports mcb3_zio]

##################################
# Chandler dbg pin
#set_property PACKAGE_PIN H17 [get_ports dbg_mcb_drp_clk]
# C:/chandler/PROJ/shzte/20111208_mcberror/reference_designs/sp601_mig_prebuilt_example_design/rtl/example_top.ucf:203
# The conversion of 'IOSTANDARD' constraint on 'net' object 'dbg_mcb_drp_clk' has been applied to the port object 'dbg_mcb_drp_clk'.
#set_property IOSTANDARD LVCMOS25 [get_ports dbg_mcb_drp_clk]
